const state={files:{'index.html':`<!doctype html>\n<html>\n<head><meta charset="utf-8"><title>FluxCode Project</title></head>\n<body><main><h1>Hello from FluxCode ✦</h1><p>Edit this file and press Run.</p></main></body>\n</html>`,'style.css':`body{font-family:system-ui;margin:0;min-height:100vh;display:grid;place-items:center;background:#0d1020;color:white}main{text-align:center;padding:48px;border-radius:24px;background:#ffffff12;backdrop-filter:blur(20px)}h1{font-size:42px;margin:0 0 12px}`,'app.js':`console.log("FluxCode project running");`},current:'index.html',sha:null,repo:null,owner:null,theme:'midnight',fontSize:13,autoSave:true};
const $=s=>document.querySelector(s),code=$('#code'),frame=$('#frame'),terminal=$('#terminal'),modal=$('#modal'),body=$('#modalBody');
const langs={html:['HTML','index.html'],css:['CSS','style.css'],js:['JavaScript','app.js'],ts:['TypeScript','main.ts'],py:['Python','main.py'],java:['Java','Main.java'],cpp:['C++','main.cpp'],c:['C','main.c'],cs:['C#','Program.cs'],rs:['Rust','main.rs'],go:['Go','main.go'],php:['PHP','index.php'],rb:['Ruby','main.rb'],swift:['Swift','main.swift'],kt:['Kotlin','Main.kt'],lua:['Lua','main.lua'],sql:['SQL','query.sql'],sh:['Shell','script.sh'],json:['JSON','data.json'],md:['Markdown','README.md']};
function languageFor(path){const ext=(path.split('.').pop()||'').toLowerCase();return langs[ext]?.[0]||'Plain Text'}
function renderFiles(){const list=$('#fileList');list.innerHTML='';Object.keys(state.files).forEach(name=>{const b=document.createElement('button');b.className='file'+(name===state.current?' active':'');b.textContent='◇ '+name;b.onclick=()=>{state.current=name;renderCode()};list.appendChild(b)})}
function renderCode(){code.textContent=state.files[state.current]||'';$('#fileName').textContent=state.current;$('#languageLabel').textContent=languageFor(state.current);$('#activeTab').textContent=state.current;code.style.fontSize=state.fontSize+'px';renderFiles()}
function preview(){const html=(state.files['index.html']||'').replace('</head>',`<style>${state.files['style.css']||''}</style></head>`).replace('</body>',`<script>${state.files['app.js']||''}<\/script></body>`);frame.srcdoc=html;terminal.textContent=`FluxCode workspace ready.\n$ flux run\n✓ Live preview updated for ${state.current}\n`}
function show(title,text,fields=''){body.innerHTML=`<h2>${title}</h2><p>${text}</p>${fields}<button class="primary" id="modalAction">Continue</button>`;modal.classList.remove('hidden')}
function settings(){body.innerHTML=`<h2>Settings</h2><p>Make FluxCode yours.</p><div class="settings-grid"><div class="setting-row"><span>Appearance</span><button id="themeBtn">${state.theme==='midnight'?'Midnight Glass':'Light Glass'}</button></div><div class="setting-row"><span>Editor font size</span><button id="fontBtn">${state.fontSize}px</button></div><div class="setting-row"><span>Auto-save</span><button id="autoBtn">${state.autoSave?'On':'Off'}</button></div><div class="setting-row"><span>Reduce motion</span><button id="motionBtn">${localStorage.reduceMotion==='1'?'On':'Off'}</button></div><div class="setting-row"><span>Reset workspace</span><button id="resetBtn">Reset</button></div></div><button class="primary" id="modalAction">Done</button>`;modal.classList.remove('hidden');$('#themeBtn').onclick=()=>{state.theme=state.theme==='midnight'?'light':'midnight';document.body.classList.toggle('light',state.theme==='light');$('#themeBtn').textContent=state.theme==='midnight'?'Midnight Glass':'Light Glass'};$('#fontBtn').onclick=()=>{state.fontSize=state.fontSize>=18?12:state.fontSize+2;renderCode();$('#fontBtn').textContent=state.fontSize+'px'};$('#autoBtn').onclick=()=>{state.autoSave=!state.autoSave;$('#autoBtn').textContent=state.autoSave?'On':'Off'};$('#motionBtn').onclick=()=>{localStorage.reduceMotion=localStorage.reduceMotion==='1'?'0':'1';$('#motionBtn').textContent=localStorage.reduceMotion==='1'?'On':'Off'};$('#resetBtn').onclick=()=>{state.files={'index.html':'','style.css':'','app.js':''};state.current='index.html';renderCode();preview()}}
function githubConnect(){show('GitHub','Your fine-grained token is stored encrypted by the operating system. Use repository Contents read/write access.','<input id="ghToken" type="password" placeholder="GitHub fine-grained token">')}
function cloudConnect(){show('Cloudflare','Connect your account to manage Workers, Pages, D1, KV and more.','<input id="cfToken" type="password" placeholder="Cloudflare API token"><input id="cfAccount" placeholder="Cloudflare Account ID">')}
function newProject(){show('New Project','Choose a language. FluxCode will create the starter files for you.',`<div id="projectChoices">${Object.entries(langs).map(([k,v])=>`<button class="project-choice" data-lang="${k}">${v[0]} <span>· ${v[1]}</span></button>`).join('')}</div>`);document.querySelectorAll('[data-lang]').forEach(b=>b.onclick=()=>createProject(b.dataset.lang))}
function createProject(k){const [label,file]=langs[k];const templates={html:`<!doctype html>\n<html>\n<head><meta charset="utf-8"><title>New ${label} Project</title></head>\n<body>\n  <h1>Hello from FluxCode</h1>\n</body>\n</html>`,css:'/* Your CSS project */\n',js:'console.log("Hello from FluxCode");\n',ts:'const message: string = "Hello from FluxCode";\nconsole.log(message);\n',py:'print("Hello from FluxCode")\n',json:'{\n  "name": "FluxCode Project"\n}\n',md:'# FluxCode Project\n\nStart building here.\n'};state.files={};state.files[file]=templates[k]||`// ${label} project\n// Created with FluxCode\n`;if(k==='html'){state.files['style.css']='';state.files['app.js']=''}state.current=file;state.repo=null;state.owner=null;state.sha=null;$('#projectName').textContent='Untitled '+label+' Project';$('#repoStatus').textContent='Local workspace';modal.classList.add('hidden');renderCode();preview()}
async function loadRepos(){try{const repos=await window.flux.github.repos();const list=repos.map(r=>`<button class="project-choice" data-repo="${r.full_name}">◈ ${r.name}<span> · ${r.private?'Private':'Public'}</span></button>`).join('')||'<p>No repositories found.</p>';show('Your GitHub repositories','Choose a repository to open it in FluxCode.',`<div id="repoList">${list}</div>`);document.querySelectorAll('[data-repo]').forEach(b=>b.onclick=()=>openRepo(b.dataset.repo))}catch(e){show('GitHub error',e.message)}}
async function openRepo(full){const [owner,repo]=full.split('/');try{const tree=await window.flux.github.tree(owner,repo);const files=tree.tree.filter(x=>x.type==='blob').map(x=>`<button class="project-choice" data-path="${x.path}">◇ ${x.path}</button>`).join('');state.owner=owner;state.repo=repo;state.sha=null;$('#projectName').textContent=repo;$('#repoStatus').textContent=full;show(repo,'Select a file to load it.',`<div id="repoFiles">${files}</div>`);document.querySelectorAll('[data-path]').forEach(b=>b.onclick=()=>openFile(owner,repo,b.dataset.path))}catch(e){show('Repository error',e.message)}}
async function openFile(owner,repo,path){try{const f=await window.flux.github.file(owner,repo,path);const text=atob(f.content.replace(/\n/g,''));state.current=path;state.files[path]=text;state.sha=f.sha;renderCode();modal.classList.add('hidden');terminal.textContent=`Loaded ${path} from ${owner}/${repo}.\n`}catch(e){show('File error',e.message)}}
async function publish(){if(!state.owner||!state.repo||!state.current){show('Publish','Open a GitHub repository and file first.');return}try{const r=await window.flux.github.commit(state.owner,state.repo,state.current,state.files[state.current],`FluxCode: update ${state.current}`,state.sha||undefined,'main');state.sha=r.content.sha;terminal.textContent+=`✓ Published ${state.current} to ${state.owner}/${state.repo}\n`}catch(e){show('Publish failed',e.message)}}
code.contentEditable='true';code.spellcheck=false;code.addEventListener('input',()=>{state.files[state.current]=code.innerText;if(state.autoSave)localStorage.setItem('fluxcodeWorkspace',JSON.stringify({files:state.files,current:state.current}))});
$('#runBtn').onclick=preview;$('#refresh').onclick=preview;$('#githubBtn').onclick=loadRepos;$('#cloudBtn').onclick=cloudConnect;$('#newProjectBtn').onclick=newProject;$('#newFile').onclick=()=>{const n=prompt('New file name (example: main.py)');if(n){state.files[n]='';state.current=n;renderCode()}};$('#close').onclick=()=>modal.classList.add('hidden');$('#newTab').onclick=()=>$('#newFile').click();document.querySelectorAll('.nav').forEach(n=>n.onclick=()=>{document.querySelectorAll('.nav').forEach(x=>x.classList.remove('active'));n.classList.add('active');if(n.dataset.panel==='preview')preview();if(n.dataset.panel==='github')loadRepos();if(n.dataset.panel==='cloud')cloudConnect();if(n.dataset.panel==='settings')settings()});
$('#winClose').onclick=()=>window.flux.window.close();$('#winMin').onclick=()=>window.flux.window.minimize();$('#winMax').onclick=()=>window.flux.window.maximize();
modal.addEventListener('click',async e=>{if(e.target.id!=='modalAction')return;try{if($('#ghToken')){await window.flux.secretSet('githubToken',$('#ghToken').value);const me=await window.flux.github.me();$('#repoStatus').textContent=`GitHub: ${me.login}`;modal.classList.add('hidden');await loadRepos();return}if($('#cfToken')){await window.flux.secretSet('cloudflareToken',$('#cfToken').value);await window.flux.set('cloudflareAccount',$('#cfAccount').value);const a=await window.flux.cloudflare.accounts();$('#repoStatus').textContent=`Cloudflare: ${a.result?.length||0} account(s)`;modal.classList.add('hidden');return}modal.classList.add('hidden')}catch(err){show('Connection failed',err.message)}});
try{const saved=JSON.parse(localStorage.getItem('fluxcodeWorkspace')||'null');if(saved?.files){state.files=saved.files;state.current=saved.current||Object.keys(state.files)[0]}}catch{}renderCode();preview();
