const state={files:{'index.html':`<!doctype html>\n<html>\n<head><meta charset="utf-8"><title>FluxCode Project</title></head>\n<body>\n  <main><h1>Hello from FluxCode ✦</h1><p>Edit this file and press Run.</p></main>\n</body>\n</html>`, 'style.css':`body{font-family:system-ui;margin:0;min-height:100vh;display:grid;place-items:center;background:#0d1020;color:white}main{text-align:center;padding:48px;border-radius:24px;background:#ffffff12;backdrop-filter:blur(20px)}h1{font-size:42px;margin:0 0 12px}`, 'app.js':`console.log("FluxCode project running");`},current:'index.html'};
const $=s=>document.querySelector(s);const code=$('#code');const frame=$('#frame');const terminal=$('#terminal');
function renderCode(){code.textContent=state.files[state.current];$('#fileName').textContent=state.current;document.querySelectorAll('.file').forEach(x=>x.classList.toggle('active',x.dataset.file===state.current));}
function preview(){const html=state.files['index.html'].replace('</head>',`<style>${state.files['style.css']}</style></head>`).replace('</body>',`<script>${state.files['app.js']}<\/script></body>`);frame.srcdoc=html;terminal.textContent=`FluxCode workspace ready.\n$ flux run\n✓ Live preview updated for ${state.current}\n`;}
code.contentEditable='true';code.spellcheck=false;code.addEventListener('input',()=>state.files[state.current]=code.innerText);
document.querySelectorAll('.file').forEach(x=>x.onclick=()=>{state.current=x.dataset.file;renderCode()});
$('#runBtn').onclick=preview;$('#refresh').onclick=preview;$('#newFile').onclick=()=>{const n=prompt('New file name (example: main.py)');if(n){state.files[n]='';state.current=n;const b=document.createElement('button');b.className='file active';b.dataset.file=n;b.textContent='◇ '+n;b.onclick=()=>{state.current=n;renderCode()};document.querySelector('.files').appendChild(b);renderCode()}};
const modal=$('#modal'),body=$('#modalBody');$('#close').onclick=()=>modal.classList.add('hidden');
function show(title,text,fields=''){body.innerHTML=`<h2>${title}</h2><p>${text}</p>${fields}<button class="primary" id="modalAction">Continue</button>`;modal.classList.remove('hidden');}
$('#githubBtn').onclick=()=>show('GitHub','Connect your GitHub account to clone repositories, edit files, create commits and publish changes.','<input id="ghToken" type="password" placeholder="GitHub token (stored encrypted on this device)">');
$('#cloudBtn').onclick=()=>show('Cloudflare','Connect Cloudflare to manage Workers, Pages, KV, D1 and other infrastructure from FluxCode.','<input id="cfToken" type="password" placeholder="Cloudflare API token (stored encrypted)"><input id="cfAccount" placeholder="Cloudflare Account ID">');
modal.addEventListener('click',async e=>{if(e.target.id!=='modalAction')return;if($('#ghToken')){await window.flux.secretSet('githubToken',$('#ghToken').value);$('#repoStatus').textContent='GitHub credentials saved locally';}if($('#cfToken')){await window.flux.secretSet('cloudflareToken',$('#cfToken').value);await window.flux.set('cloudflareAccount',$('#cfAccount').value);$('#repoStatus').textContent='Cloudflare credentials saved locally';}modal.classList.add('hidden')});
document.querySelectorAll('.nav').forEach(n=>n.onclick=()=>{if(n.dataset.panel==='preview')preview();if(n.dataset.panel==='github')$('#githubBtn').click();if(n.dataset.panel==='cloud')$('#cloudBtn').click()});
renderCode();preview();
