const state={files:{'index.html':`<!doctype html>\n<html>\n<head><meta charset="utf-8"><title>FluxCode Project</title></head>\n<body><main><h1>Hello from FluxCode ✦</h1><p>Edit this file and press Run.</p></main></body>\n</html>`,'style.css':'body{font-family:system-ui;margin:0;min-height:100vh;display:grid;place-items:center;background:#0d1020;color:white}','app.js':'console.log("FluxCode project running");'},current:'index.html',sha:null,repo:null,owner:null,theme:localStorage.getItem('fluxcodeTheme')||'midnight',fontSize:13,autoSave:true};
const $=s=>document.querySelector(s),code=$('#code'),frame=$('#frame'),terminal=$('#terminal'),modal=$('#modal'),body=$('#modalBody');
const langs={html:['HTML','index.html'],css:['CSS','style.css'],js:['JavaScript','app.js'],ts:['TypeScript','main.ts'],py:['Python','main.py'],java:['Java','Main.java'],cpp:['C++','main.cpp'],c:['C','main.c'],cs:['C#','Program.cs'],rs:['Rust','main.rs'],go:['Go','main.go'],php:['PHP','index.php'],rb:['Ruby','main.rb'],swift:['Swift','main.swift'],kt:['Kotlin','Main.kt'],lua:['Lua','main.lua'],sql:['SQL','query.sql'],sh:['Shell','script.sh'],json:['JSON','data.json'],md:['Markdown','README.md'],flux:['Flux','main.flux']};
function languageFor(path){const ext=(path.split('.').pop()||'').toLowerCase();return langs[ext]?.[0]||'Plain Text'}
function applyAppearance(){const light=state.theme==='light';document.body.classList.toggle('light',light);document.documentElement.classList.toggle('light',light);document.documentElement.style.setProperty('--editor-size',state.fontSize+'px');localStorage.setItem('fluxcodeTheme',state.theme)}
function renderFiles(){const list=$('#fileList');list.innerHTML='';Object.keys(state.files).forEach(name=>{const b=document.createElement('button');b.className='file'+(name===state.current?' active':'');b.textContent='◇ '+name;b.onclick=()=>{state.current=name;renderCode()};list.appendChild(b)})}
function renderCode(){code.textContent=state.files[state.current]||'';$('#fileName').textContent=state.current;$('#languageLabel').textContent=languageFor(state.current);$('#activeTab').textContent=state.current;code.style.fontSize=state.fontSize+'px';renderFiles()}
function preview(){if(state.current.endsWith('.flux')){runFlux();return}const html=(state.files['index.html']||'').replace('</head>',`<style>${state.files['style.css']||''}</style></head>`).replace('</body>',`<script>${state.files['app.js']||''}<\/script></body>`);frame.srcdoc=html;terminal.textContent=`FluxCode workspace ready.\n$ flux run\n✓ Live preview updated for ${state.current}\n`}
async function runFlux(){const src=state.files[state.current]||'';terminal.textContent=`Flux runtime\n$ flux run ${state.current}\n`;if(!window.FluxRuntime){terminal.textContent+='✗ Flux runtime failed to load.\n';return}const result=await window.FluxRuntime.run(src,{print:(...x)=>{terminal.textContent+=x.map(String).join(' ')+'\n'}});if(result.output)terminal.textContent+=result.output+'\n';if(result.error)terminal.textContent+=`✗ ${result.error}\n`;else terminal.textContent+='✓ Program finished.\n';}
function show(title,text,fields='',action='Continue'){body.innerHTML=`<h2>${title}</h2><p>${text}</p>${fields}<button class="primary" id="modalAction">${action}</button>`;modal.classList.remove('hidden')}
const fluxCourse=[
['01 · Welcome to Flux','Flux is the native language of FluxCode. It is designed to be readable, fast to learn and expressive. Your first program:',`print("Hello, Flux!")`],
['02 · Values and variables','Use let for a changeable value and const for a value you intend to keep stable.',`let name = "Joel";\nlet score = 100;\nprint(name, score);`],
['03 · Math','Flux supports +, -, *, /, %, comparisons and boolean operators.',`let total = 12 * 8 + 4;\nprint(total);\nprint(sqrt(81));`],
['04 · Decisions','Use if and else to make choices.',`let age = 12;\nif (age >= 13) {\n  print("Teen");\n} else {\n  print("Not quite yet");\n}`],
['05 · Loops','while repeats code. Flux includes a safety limit so an accidental infinite loop cannot lock the app.',`let n = 1;\nwhile (n <= 5) {\n  print(n);\n  n = n + 1;\n}`],
['06 · Functions','Functions package reusable behaviour.',`fn greet(name) {\n  print("Hello", name);\n}\ngreet("Flux developer");`],
['07 · Lists','Create lists with square brackets. len() gets their size and range() creates number sequences.',`let nums = [10, 20, 30];\nprint(len(nums));\nprint(range(5));`],
['08 · Built-ins','Flux has useful built-ins for maths, random values and timestamps.',`print(abs(-9));\nprint(round(3.7));\nprint(random());\nprint(now());`],
['09 · Build real projects','Flux projects use the .flux extension. Create a Flux project from New Project, write code in main.flux, then press Run.'],
['10 · The Flux mindset','Build small pieces, test them, turn repeated logic into functions, and keep your programs readable.'],
['11 · What Flux can become','The current runtime is the safe core. Future Flux releases can add modules, richer data structures, async APIs, package management, a compiler, native tooling and more without changing the basic language experience.']
];
function learnFlux(){body.innerHTML=`<div class="learn-hero"><h2>⚡ Learn Flux</h2><p>A big, built-in course for the Flux programming language. Work through the chapters, copy examples into a .flux project, and press Run.</p></div><div class="course">${fluxCourse.map(c=>`<article class="course-card"><h3>${c[0]}</h3><p>${c[1]}</p>${c[2]?`<code class="flux-code">${escapeHtml(c[2])}</code><button class="project-choice course-run" data-code="${encodeURIComponent(c[2])}">▶ Try this example</button>`:''}</article>`).join('')}</div><button class="primary" id="modalAction">Close course</button>`;modal.classList.remove('hidden');document.querySelectorAll('.course-run').forEach(b=>b.onclick=()=>{createFluxProject();state.files['main.flux']=decodeURIComponent(b.dataset.code);state.current='main.flux';modal.classList.add('hidden');renderCode();runFlux()})}
function escapeHtml(s){return s.replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;')}
function settings(){body.innerHTML=`<h2>Settings</h2><p>Make FluxCode yours.</p><div class="settings-grid"><div class="setting-row"><span>Appearance</span><button id="themeBtn">${state.theme==='midnight'?'Midnight Glass':'Light Glass'}</button></div><div class="setting-row"><span>Editor font size</span><button id="fontBtn">${state.fontSize}px</button></div><div class="setting-row"><span>Auto-save</span><button id="autoBtn">${state.autoSave?'On':'Off'}</button></div><div class="setting-row"><span>Reduce motion</span><button id="motionBtn">${localStorage.reduceMotion==='1'?'On':'Off'}</button></div><div class="setting-row update-setting"><div><strong>FluxCode Updates</strong><small id="updateStatus">Check for a newer release.</small></div><button id="updateBtn">Check for Updates</button></div><div class="setting-row"><span>Reset workspace</span><button id="resetBtn">Reset</button></div></div><button class="primary" id="modalAction">Done</button>`;modal.classList.remove('hidden');$('#themeBtn').onclick=()=>{state.theme=state.theme==='midnight'?'light':'midnight';applyAppearance();$('#themeBtn').textContent=state.theme==='midnight'?'Midnight Glass':'Light Glass'};$('#fontBtn').onclick=()=>{state.fontSize=state.fontSize>=18?12:state.fontSize+2;renderCode();$('#fontBtn').textContent=state.fontSize+'px'};$('#autoBtn').onclick=()=>{state.autoSave=!state.autoSave;$('#autoBtn').textContent=state.autoSave?'On':'Off'};$('#motionBtn').onclick=()=>{localStorage.reduceMotion=localStorage.reduceMotion==='1'?'0':'1';$('#motionBtn').textContent=localStorage.reduceMotion==='1'?'On':'Off';document.documentElement.classList.toggle('reduce-motion',localStorage.reduceMotion==='1')};$('#resetBtn').onclick=()=>{state.files={'index.html':'','style.css':'','app.js':''};state.current='index.html';renderCode();preview()};$('#updateBtn').onclick=checkUpdates}
async function checkUpdates(){const status=$('#updateStatus'),button=$('#updateBtn');if(!status||!button)return;status.textContent='Checking…';button.disabled=true;try{const r=await window.flux.updates.check();if(r?.development)status.textContent='Install the released FluxCode app to use updates.'}catch(e){status.textContent=e.message||'Could not check for updates.'}finally{button.disabled=false}}
function updateAvailable(info){const s=$('#updateStatus'),b=$('#updateBtn');if(!s)return;s.textContent=`Version ${info.version} is available.`;b.textContent='Download Update';b.disabled=false;b.onclick=async()=>{b.disabled=true;b.textContent='Downloading…';try{await window.flux.updates.download()}catch(e){s.textContent=e.message||'Download failed.';b.disabled=false;b.textContent='Check for Updates';b.onclick=checkUpdates}}}
function updateDownloaded(info){const s=$('#updateStatus'),b=$('#updateBtn');if(!s)return;s.textContent=`FluxCode ${info.version} is ready to install.`;b.disabled=false;b.textContent='Restart & Install';b.onclick=()=>window.flux.updates.install()}
window.flux.updates.on('checking',()=>{const s=$('#updateStatus');if(s)s.textContent='Checking for updates…'});window.flux.updates.on('available',updateAvailable);window.flux.updates.on('not-available',()=>{const s=$('#updateStatus'),b=$('#updateBtn');if(s)s.textContent='You’re up to date.';if(b){b.disabled=false;b.textContent='Check for Updates';b.onclick=checkUpdates}});window.flux.updates.on('downloaded',updateDownloaded);window.flux.updates.on('error',message=>{const s=$('#updateStatus'),b=$('#updateBtn');if(s)s.textContent=`Update error: ${message}`;if(b){b.disabled=false;b.textContent='Check for Updates';b.onclick=checkUpdates}});window.flux.updates.on('progress',p=>{const s=$('#updateStatus');if(s)s.textContent=`Downloading update… ${Math.round(p.percent)}%`});
function githubConnect(){show('GitHub','Your fine-grained token is stored encrypted by the operating system. Use repository Contents read/write access.','<input id="ghToken" type="password" placeholder="GitHub fine-grained token">')}
function cloudConnect(){show('Cloudflare','Connect your account to manage Workers, Pages, D1, KV and more.','<input id="cfToken" type="password" placeholder="Cloudflare API token"><input id="cfAccount" placeholder="Cloudflare Account ID">')}
function newProject(){show('New Project','Choose a language. Flux is built into FluxCode and runs without another language installation.',`<div id="projectChoices">${Object.entries(langs).map(([k,v])=>`<button class="project-choice" data-lang="${k}">${v[0]} <span>· ${v[1]}</span></button>`).join('')}</div>`);document.querySelectorAll('[data-lang]').forEach(b=>b.onclick=()=>b.dataset.lang==='flux'?createFluxProject():createProject(b.dataset.lang))}
function createFluxProject(){state.files={'main.flux':`print("Hello from Flux!")\n\nlet name = "Flux developer"\nprint("Welcome", name)\n\nfn square(n) {\n  return n * n\n}\n\nprint("9 squared =", square(9))\n`};state.current='main.flux';state.repo=null;state.owner=null;state.sha=null;$('#projectName').textContent='Untitled Flux Project';$('#repoStatus').textContent='Flux language · local project';modal.classList.add('hidden');renderCode();runFlux()}
function createProject(k){const [label,file]=langs[k];const templates={html:`<!doctype html>\n<html>\n<head><meta charset="utf-8"><title>New ${label} Project</title></head>\n<body><h1>Hello from FluxCode</h1></body>\n</html>`,css:'/* Your CSS project */\n',js:'console.log("Hello from FluxCode");\n',ts:'const message: string = "Hello from FluxCode";\nconsole.log(message);\n',py:'print("Hello from FluxCode")\n',json:'{\n  "name": "FluxCode Project"\n}\n',md:'# FluxCode Project\n\nStart building here.\n'};state.files={};state.files[file]=templates[k]||`// ${label} project\n// Created with FluxCode\n`;if(k==='html'){state.files['style.css']='';state.files['app.js']=''}state.current=file;state.repo=null;state.owner=null;state.sha=null;$('#projectName').textContent='Untitled '+label+' Project';$('#repoStatus').textContent='Local workspace';modal.classList.add('hidden');renderCode();preview()}
async function loadRepos(){try{const repos=await window.flux.github.repos();const list=repos.map(r=>`<button class="project-choice" data-repo="${r.full_name}">◈ ${r.name}<span> · ${r.private?'Private':'Public'}</span></button>`).join('')||'<p>No repositories found.</p>';show('Your GitHub repositories','Choose a repository to open it in FluxCode.',`<div id="repoList">${list}</div>`);document.querySelectorAll('[data-repo]').forEach(b=>b.onclick=()=>openRepo(b.dataset.repo))}catch(e){show('GitHub error',e.message)}}
async function openRepo(full){const [owner,repo]=full.split('/');try{const tree=await window.flux.github.tree(owner,repo);const files=tree.tree.filter(x=>x.type==='blob').map(x=>`<button class="project-choice" data-path="${x.path}">◇ ${x.path}</button>`).join('');state.owner=owner;state.repo=repo;state.sha=null;$('#projectName').textContent=repo;$('#repoStatus').textContent=full;show(repo,'Select a file to load it.',`<div id="repoFiles">${files}</div>`);document.querySelectorAll('[data-path]').forEach(b=>b.onclick=()=>openFile(owner,repo,b.dataset.path))}catch(e){show('Repository error',e.message)}}
async function openFile(owner,repo,path){try{const f=await window.flux.github.file(owner,repo,path);const text=atob(f.content.replace(/\n/g,''));state.current=path;state.files[path]=text;state.sha=f.sha;renderCode();modal.classList.add('hidden');terminal.textContent=`Loaded ${path} from ${owner}/${repo}.\n`}catch(e){show('File error',e.message)}}
async function publish(){if(!state.owner||!state.repo||!state.current){show('Publish','Open a GitHub repository and file first.');return}try{const r=await window.flux.github.commit(state.owner,state.repo,state.current,state.files[state.current],`FluxCode: update ${state.current}`,state.sha||undefined,'main');state.sha=r.content.sha;terminal.textContent+=`✓ Published ${state.current} to ${state.owner}/${state.repo}\n`}catch(e){show('Publish failed',e.message)}}
code.contentEditable='true';code.spellcheck=false;code.addEventListener('input',()=>{state.files[state.current]=code.innerText;if(state.autoSave)localStorage.setItem('fluxcodeWorkspace',JSON.stringify({files:state.files,current:state.current}))});
$('#runBtn').onclick=preview;$('#refresh').onclick=preview;$('#githubBtn').onclick=loadRepos;$('#cloudBtn').onclick=cloudConnect;$('#newProjectBtn').onclick=newProject;$('#learnFluxBtn').onclick=learnFlux;$('#learnFluxSide').onclick=learnFlux;$('#newFile').onclick=()=>{const n=prompt('New file name (example: main.flux)');if(n){state.files[n]='';state.current=n;renderCode()}};$('#close').onclick=()=>modal.classList.add('hidden');$('#newTab').onclick=()=>$('#newFile').click();document.querySelectorAll('.nav').forEach(n=>n.onclick=()=>{document.querySelectorAll('.nav').forEach(x=>x.classList.remove('active'));n.classList.add('active');if(n.dataset.panel==='preview')preview();if(n.dataset.panel==='github')loadRepos();if(n.dataset.panel==='cloud')cloudConnect();if(n.dataset.panel==='settings')settings()});
$('#winClose').onclick=()=>window.flux.window.close();$('#winMin').onclick=()=>window.flux.window.minimize();$('#winMax').onclick=()=>window.flux.window.maximize();
modal.addEventListener('click',async e=>{if(e.target.id!=='modalAction')return;try{if($('#ghToken')){await window.flux.secretSet('githubToken',$('#ghToken').value);const me=await window.flux.github.me();$('#repoStatus').textContent=`GitHub: ${me.login}`;modal.classList.add('hidden');await loadRepos();return}if($('#cfToken')){await window.flux.secretSet('cloudflareToken',$('#cfToken').value);await window.flux.set('cloudflareAccount',$('#cfAccount').value);const a=await window.flux.cloudflare.accounts();$('#repoStatus').textContent=`Cloudflare: ${a.result?.length||0} account(s)`;modal.classList.add('hidden');return}modal.classList.add('hidden')}catch(err){show('Connection failed',err.message)}});
try{const saved=JSON.parse(localStorage.getItem('fluxcodeWorkspace')||'null');if(saved?.files){state.files=saved.files;state.current=saved.current||Object.keys(state.files)[0]}}catch{}applyAppearance();renderCode();preview();
