// Flux language runtime for FluxCode.
// Flux is a small, expressive, beginner-friendly scripting language that runs safely inside the FluxCode renderer.
(function(){
  const TOKEN=/\s*(?:(\d+(?:\.\d+)?)|("(?:\\.|[^"\\])*"|'(?:\\.|[^'\\])*')|([A-Za-z_][A-Za-z0-9_]*)|(==|!=|<=|>=|&&|\|\||=>|[+\-*\/%<>=!(){}\[\],;.?:]))/y;
  function lex(src){let out=[],i=0;while(i<src.length){TOKEN.lastIndex=i;const m=TOKEN.exec(src);if(!m){if(src.slice(i).trim()==='')break;throw new Error(`Flux syntax error near: ${src.slice(i,i+24)}`)}i=TOKEN.lastIndex;if(m[1])out.push(['num',Number(m[1])]);else if(m[2])out.push(['str',JSON.parse(m[2][0]==='"'?m[2]:`"${m[2].slice(1,-1).replace(/"/g,'\\"')}"`)]);else if(m[3])out.push(['id',m[3]]);else out.push(['op',m[4]])}out.push(['eof','']);return out}
  class Parser{constructor(src){this.t=lex(src);this.i=0}peek(v){return this.t[this.i][1]===v}next(){return this.t[this.i++]}eat(v){if(!this.peek(v))throw new Error(`Expected '${v}'`);return this.next()}program(){const a=[];while(!this.peek('')&&!this.peek('}'))a.push(this.stmt());return a}stmt(){if(this.peek(';')){this.next();return{t:'empty'}}if(this.peek('let')||this.peek('const')){this.next();const n=this.next()[1];let v={t:'lit',v:null};if(this.peek('=')){this.next();v=this.expr()}this.peek(';')&&this.next();return{t:'var',n,v}}if(this.peek('print')){this.next();this.eat('(');const e=[];if(!this.peek(')')){do{e.push(this.expr())}while(this.peek(',')&&this.next())}this.eat(')');this.peek(';')&&this.next();return{t:'print',e}}if(this.peek('if')){this.next();this.eat('(');const c=this.expr();this.eat(')');this.eat('{');const yes=this.program();this.eat('}');let no=[];if(this.peek('else')){this.next();this.eat('{');no=this.program();this.eat('}')}return{t:'if',c,yes,no}}if(this.peek('while')){this.next();this.eat('(');const c=this.expr();this.eat(')');this.eat('{');const b=this.program();this.eat('}');return{t:'while',c,b}}if(this.peek('fn')){this.next();const n=this.next()[1];this.eat('(');const p=[];if(!this.peek(')')){do{p.push(this.next()[1])}while(this.peek(',')&&this.next())}this.eat(')');this.eat('{');const b=this.program();this.eat('}');return{t:'fn',n,p,b}}if(this.peek('return')){this.next();const e=this.peek(';')?{t:'lit',v:null}:this.expr();this.peek(';')&&this.next();return{t:'return',e}}const e=this.expr();this.peek(';')&&this.next();return{t:'expr',e}}expr(){return this.binary(0)}binary(min){let l=this.unary();const prec={'||':1,'&&':2,'==':3,'!=':3,'<':4,'>':4,'<=':4,'>=':4,'+':5,'-':5,'*':6,'/':6,'%':6};while(true){const op=this.t[this.i][1],p=prec[op]??-1;if(p<min)break;this.next();const r=this.binary(p+1);l={t:'bin',op,l,r}}return l}unary(){if(['!','-'].includes(this.t[this.i][1])){const op=this.next()[1];return{t:'un',op,e:this.unary()}}return this.primary()}primary(){const [k,v]=this.next();if(k==='num'||k==='str')return{t:'lit',v};if(v==='true'||v==='false'||v==='null')return{t:'lit',v:v==='true'?true:v==='false'?false:null};if(v==='('){const e=this.expr();this.eat(')');return e}if(k==='id'){let e={t:'id',n:v};if(this.peek('(')){this.next();const a=[];if(!this.peek(')')){do{a.push(this.expr())}while(this.peek(',')&&this.next())}this.eat(')');e={t:'call',fn:e,args:a}}return e}if(v==='['){const a=[];if(!this.peek(']')){do{a.push(this.expr())}while(this.peek(',')&&this.next())}this.eat(']');return{t:'array',a}}throw new Error(`Unexpected '${v}'`)}}
  class Env{constructor(parent=null){this.parent=parent;this.v=Object.create(null)}get(k){if(k in this.v)return this.v[k];if(this.parent)return this.parent.get(k);throw new Error(`Unknown Flux name: ${k}`)}set(k,v){this.v[k]=v}}
  async function run(src,api={print:console.log}){const ast=new Parser(src).program(),root=new Env();const out=[];const log=(...x)=>{out.push(x.map(v=>typeof v==='object'?JSON.stringify(v):String(v)).join(' '));api.print?.(...x)};root.set('print',(...x)=>log(...x));root.set('len',x=>x?.length??0);root.set('range',(n)=>Array.from({length:Number(n)},(_,i)=>i));root.set('sqrt',Math.sqrt);root.set('round',Math.round);root.set('floor',Math.floor);root.set('ceil',Math.ceil);root.set('abs',Math.abs);root.set('random',Math.random);root.set('now',()=>new Date().toISOString());
    async function ev(e,env){switch(e.t){case'lit':return e.v;case'id':return env.get(e.n);case'array':return Promise.all(e.a.map(x=>ev(x,env)));case'un':{const v=await ev(e.e,env);return e.op==='!'?!v:-v}case'bin':{const a=await ev(e.l,env),b=await ev(e.r,env);return({'+' :a+b,'-':a-b,'*':a*b,'/':a/b,'%':a%b,'==':a==b,'!=':a!=b,'<':a<b,'>':a>b,'<=':a<=b,'>=':a>=b,'&&':a&&b,'||':a||b})[e.op]}case'call':{const f=await ev(e.fn,env),args=[];for(const x of e.args)args.push(await ev(x,env));if(typeof f!=='function')throw new Error(`${e.fn.n} is not callable`);return await f(...args)}}}
    async function exec(stmts,env){for(const s of stmts){switch(s.t){case'empty':break;case'var':env.set(s.n,await ev(s.v,env));break;case'print':log(...await Promise.all(s.e.map(x=>ev(x,env))));break;case'expr':await ev(s.e,env);break;case'if':if(await ev(s.c,env))await exec(s.yes,new Env(env));else await exec(s.no,new Env(env));break;case'while':{let guard=0;while(await ev(s.c,env)){if(++guard>100000)throw new Error('Flux safety limit: while loop exceeded 100,000 iterations');await exec(s.b,new Env(env))}break}case'fn':env.set(s.n,async(...args)=>{const e=new Env(env);s.p.forEach((p,i)=>e.set(p,args[i]));try{await exec(s.b,e)}catch(x){if(x&&x.__return)return x.value;throw x}});break;case'return':throw{__return:true,value:await ev(s.e,env)}}}}
    try{await exec(ast,root);return{output:out.join('\n')}}catch(e){return{output:out.join('\n'),error:e.message||String(e)}}
  }
  window.FluxRuntime={run};
})();
